### ISSUE TITLE
Bugs in Serializing Objects

### ISSUE THREAD

**Issue by goelayu** [ZZZXie/JavaScript_Serializer#1]
The following simple base case doesn't work:

```
a = {key: "value"}
stra = {}
serializeObject(a,stra);
newa = {}
deserializeObject(stra, newa) // newa == {}
```

You might want to correct the following things for starter:
 - [here](https://github.com/ZZZXie/JavaScript_Serializer/blob/master/CompletedSerializer.js#L209) you are saving the Objects constructor name. You should be saving the value's constructor name
 - [here](https://github.com/ZZZXie/JavaScript_Serializer/blob/master/CompletedSerializer.js#L138) instead of using `for key in` it should be `for key of`. `In` keyword  always returns the index, not the actual value 
 - [here](https://github.com/ZZZXie/JavaScript_Serializer/blob/master/CompletedSerializer.js#L141) change `Object.prototype.toString` to `Object.prototype.toString.call`, as the former will always return `[object object]`, as it doesn't read the argument.

**Comment by ZZZXie** [comment]
I have tested and resolved those bugs and made an updated version of serializer and README
